### ISSUE TITLE
not training

### ISSUE THREAD

**Issue by streamnsight** [Jwata/job-word-embeddings#1]
Hello,

Thanks for sharing this notebook. Very interesting.
Now, it seems like you are never really training the Word2Vec model. You initialize it, but you never call the `.train` method to train the model.

**Comment by Jwata** [comment]
@streamnsight Hi, thank you for your interest.
Training is done by `word2vec.Word2Vec` as it takes `inputs`.
See [Gensim's document](https://radimrehurek.com/gensim/models/word2vec.html) for more details.
